require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

# Definir versão mínima do iOS
platform :ios, min_ios_version_supported
prepare_react_native_project!

# Desabilitar warnings
inhibit_all_warnings!

target 'Inventario' do
  config = use_native_modules!

  # Configuração do React Native
  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => true,
    :fabric_enabled => false,
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    # Aplicar configurações do React Native
    react_native_post_install(installer)

    # Configurações para cada target
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        # Configurações básicas
        config.build_settings['ENABLE_BITCODE'] = 'NO'
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = min_ios_version_supported
        
        # Configurações para M1
        config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
        
        # Outras configurações
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)', 'FB_SONARKIT_ENABLED=0']
        
        # Otimizações
        config.build_settings['DEAD_CODE_STRIPPING'] = 'YES'
        config.build_settings['CLANG_ENABLE_MODULES'] = 'YES'
      end
    end
  end
end
