# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

# Desativar warnings para bibliotecas externas
INSTALLER_IGNORE_WARNINGS = true

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'Inventario' do
  config = use_native_modules!

  # Definições específicas para o Hermes
  hermes_enabled = ENV['USE_HERMES'] == nil || ENV['USE_HERMES'] == 'true'
  react_native_path = "../node_modules/react-native"

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/..",
    :hermes_enabled => hermes_enabled,
    :fabric_enabled => false # Desabilita o Fabric para evitar warnings relacionados
  )
  
  # Ajustar configuração do Pod RCTApple...
  pod 'FBLazyVector', :path => "#{react_native_path}/Libraries/FBLazyVector", :modular_headers => true

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
    
    # Desabilitar warnings de duplicação de libs
    installer.pods_project.targets.each do |target|
      if target.name == 'hermes-engine'
        target.build_configurations.each do |config|
          config.build_settings['CLANG_WARN_DUPLICATE_METHOD_MATCH'] = 'NO'
          config.build_settings['GCC_WARN_INHIBIT_ALL_WARNINGS'] = 'YES'
          config.build_settings['GCC_WARN_ABOUT_DEPRECATED_FUNCTIONS'] = 'NO'
        end
      end
      
      if target.name.include?("React-")
        target.build_configurations.each do |config|
          config.build_settings['GCC_WARN_INHIBIT_ALL_WARNINGS'] = 'YES'
          config.build_settings['CLANG_WARN_DOCUMENTATION_COMMENTS'] = 'NO'
          config.build_settings['CLANG_WARN_STRICT_PROTOTYPES'] = 'NO'
        end
      end
      
      # Definir sempre VALID_ARCHS para resolver problemas de arquitetura
      target.build_configurations.each do |config|
        config.build_settings['VALID_ARCHS'] = '$(ARCHS_STANDARD)'
      end
    end
    
    # Configurações recomendadas do Xcode
    installer.generated_projects.each do |project|
      project.build_configurations.each do |config|
        config.build_settings['CLANG_ANALYZER_LOCALIZABILITY_NONLOCALIZED'] = 'YES'
        config.build_settings['CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER'] = 'YES'
      end
    end
  end
end
